### ISSUE TITLE
wd.java脚本 对android sdk API18 以下的手机浏览器 chromedriver支持问题

### ISSUE THREAD

**Issue by Archer456** [macacajs/wd.java#12]
C:\Users\cmd>macaca -v

  1.1.2

C:\Users\cmd>macaca doctor

  Node.js checklist:

  node env: D:\nodejs\node.exe
  node version: v4.4.7

  Android checklist:

  JAVA version is `1.8.0_91`
  JAVA_HOME is set to `C:\Program Files\Java\jdk1.8.0_91`
  ANDROID_HOME is set to `D:\Android\android-sdk-windows`
  Platforms is set to `D:\Android\android-sdk-windows\platforms\android-24`
  Android tools is set to `D:\Android\android-sdk-windows\tools\android.bat`
  ANT_HOME is set to `D:\apache-ant-1.9.7`

  Installed driver list:

  android: 1.0.25
  chrome: 1.0.1
  electron: 1.1.2

adb devices -l
List of devices attached
192.168.236.101:5555   device product:vbox86p model:Samsung_Galaxy_S4___4_3___API_18___1080x1920 device:vbox86p

发现模拟器API18 以下版本的，在打开手机浏览器进行URL打开步骤 都会报错。该问题在win10 Ubuntu16.04环境下均一样。macaca server --verbose日志  发现应该是mcacaca-chrome  chromedriver驱动支持的问题。

![image](https://cloud.githubusercontent.com/assets/18392901/18301462/1c521f48-7504-11e6-921e-5133aa33775b.png)

![image](https://cloud.githubusercontent.com/assets/18392901/18301773/914a567e-7506-11e6-9dec-8838f60cc942.png)

恳请修复该支持，做UI自动化的目的之一就是覆盖更多的安卓系统版本碎片化的问题，虽然只是手机浏览器的问题 但很多混合开发模式 许多都是内嵌H5，所以至少支持
4.1.1 API16 以上的安装系统版本。目前发现 4.4.4 API19以上的脚本都正常。4.3 API18以下的就会有问题。

**Comment by xudafeng** [comment]
18-23，更低版本等着自然汰换吧
