### ISSUE TITLE
Android的isDisplay（） not implement

### ISSUE THREAD

**Issue by hustzyd** [macacajs/wd.java#30]
最新版本虽然实现了，但是永远返回的true
![Uploading QQ20160928-0@2x.png…]()

**Comment by ziczhu** [comment]
https://github.com/macacajs/uiautomator-client/commit/fc8a0a045a1307ea97f7245df906100ec5b11177

**Comment by xudafeng** [comment]
https://github.com/macacajs/macaca-android/issues/35

**Comment by xudafeng** [comment]
@hustzyd @zenzhu  :100:
