### ISSUE TITLE
iOS真机持续跑用例时经常性卡死

### ISSUE THREAD

**Issue by hustzyd** [macacajs/wd.java#35]
er-Runner.app
state->dst_bundle: /var/folders/7s/kmfmv51j779_2zg_ttf4yl340000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.J0qI9Z/WebDriverAgentRunner-Runner.app_sparse.ipa/Payload//WebDriverAgentRunner-Runner.app, binaryDiff flag: FALSE
  dst_ipa: /var/folders/7s/kmfmv51j779_2zg_ttf4yl340000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.J0qI9Z/WebDriverAgentRunner-Runner.app_sparse.ipa

> > xctest-client.js:156:14 [master] pid:48728 __MDMDirectoryDiff_block_invoke37:1473 calling writeDictToFile with: /var/folders/7s/kmfmv51j779_2zg_ttf4yl340000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.J0qI9Z/WebDriverAgentRunner-Runner.app_sparse.ipa/ManifestCache.plist
> > 
> > xctest-client.js:156:14 [master] pid:48728 writeDictToFile:1278 ==== Successfully wrote Manifest cache to /var/folders/7s/kmfmv51j779_2zg_ttf4yl340000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.J0qI9Z/WebDriverAgentRunner-Runner.app_sparse.ipa/ManifestCache.plist

**Comment by xudafeng** [comment]
https://github.com/alibaba/macaca/issues/317
