### ISSUE TITLE
建议waitForElement方法增加timeout参数传入，目前1000ms时间太短

### ISSUE THREAD

**Issue by Wanghuayin** [macacajs/wd.java#64]
如题

**Comment by Yinxl** [comment]
@Wanghuayin  可以通过driver.setWaitElementTimeout(3000)设置超时时间哦 ，另外还可以通过driver.setWaitElementTimeInterval(300)设置轮询时间间隔

**Comment by Wanghuayin** [comment]
感谢！响应速度真快
