### ISSUE TITLE
ios多设备执行 webdriver server 的router监听会导致 命令执行串掉

### ISSUE THREAD

**Issue by jasonSky** [macacajs/wd.java#65]
wda提供了返回桌面api， wd这个没有进行封装【请查看FBCustomerCommand】

**已解决**！ 修改webdriver-server router.js ， 和 macaca-ios.js
router.js
.post('/wd/hub/homescreen/:sessionId', controllers.session.home)

session.js
function *home(next) {
  const sessionId = this.params.sessionId;
  this.sessionId = sessionId;
  const device = this.devices.get(sessionId);
  yield device.backToHome();
  this.status = 200;
  yield next;
}

macaca-ios.js
IOS.prototype.backToHome = function *() {
  logger.debug('Go To Home Screen...');
  const screenUrl = `/homescreen`;
  this.xctest.sendCommand(screenUrl, 'POST', {});
};

=========================================================

Note:
waitForElement方法 有一处多余 会导致 发送多次请求 耽误测试时间
if (!elementExist) {
				// not find element ,keep searching
				this.sleep(waitElementTimeInterval);
				timeLeft -= waitElementTimeInterval;
			} else {
				// finded , break
				satisfied = true;
				_//getElement(wayToFind, value, index);  //这一行可以注销掉 因为isExise已经去find一遍了，如果找到了直接用就行，没必要再请求一遍_
				break;
			}

**Comment by jasonSky** [comment]
截图返回的字符串是什么算法？ 保存的图片打不开

**已解决**！ 修改saveScreenShot方法
JSONObject parse = (JSONObject) JSONObject.parse(takeScreenshot().toString());
byte[] b = decoder.decodeBuffer(parse.get("value").toString());

**Comment by jasonSky** [comment]
ios多设备能否实现？
router监听是不是约束点？ 是否有解决办法？

Note：
webdriverserver启动多个实例是没有问题的 但是跑的时候发送的 http请求到了 router那里就会乱掉

**Comment by jasonSky** [comment]
@xudafeng

**Comment by jasonSky** [comment]
@xudafeng

**Comment by ziczhu** [comment]
@jasonSky 那个 saveScreenShot 已经解决，你更新一下 macaca-ios 即可。

**Comment by jasonSky** [comment]
多设备的问题能帮忙看下？ @zenzhu 

报 “”Application is not running, possibly crashed“”

**Comment by ziczhu** [comment]
@jasonSky 多设备是说在用例中设了不同的 udid 吗，还是模拟器

**Comment by jasonSky** [comment]
@zenzhu  udid真机
![qq 20161208160839](https://cloud.githubusercontent.com/assets/8477313/21002456/e6e56108-bd60-11e6-86e8-e486e3c60693.png)


一个设备的时候 很稳定 
多个就是不行

**Comment by ziczhu** [comment]
把日志完整点贴上来点，不过我们之前没有设计过 iOS 多设备，不确定行不行。

**Comment by jasonSky** [comment]
等待第一个wda启动后 再跑第二个job（避免xcodebuild启动时 port问题）

[testng] Response content:{"value":[{"ELEMENT":"1F0D3457-35E8-4088-AD65-780A74E78ABE","type":"XCUIElementTypeApplication","label":"NQSky EMM"},{"ELEMENT":"B4FCCACB-0AF4-43BB-A57F-7B4C504BF612","type":"XCUIElementTypeImage","label":null},{"ELEMENT":"6AD0A7B8-7CC6-4494-80FA-B5CFD125DF9E","type":"XCUIElementTypeImage","label":null},{"ELEMENT":"E96D5B66-2A90-4302-9D4F-E191AE8AA537","type":"XCUIElementTypeButton","label":"back ...
   [testng] The command executed successfully.
   [testng] 200
   [testng] Response content:{"status":0,"id":"B14FF937-DA4C-4455-85DC-D86079E059F5","value":"","sessionId":"b2656cac-797a-403b-ad15-24fdc6f3df1b"}
   [testng] The command executed successfully.
   [testng] org.apache.http.NoHttpResponseException: localhost:3457 failed to respond
   [testng] 	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:143)
   [testng] 	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
   [testng] 	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:261)
   [testng] 	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:165)
   [testng] 	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:167)
   [testng] 	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:272)
   [testng] 	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:124)
   [testng] 	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:271)
   [testng] 	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
   [testng] 	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
   [testng] 	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
   [testng] 	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
   [testng] 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
   [testng] 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
   [testng] 	at macaca.client.common.Utils.postRequest(Utils.java:93)
   [testng] 	at macaca.client.common.Utils.request(Utils.java:143)
   [testng] 	at macaca.client.commands.Element.findElements(Element.java:64)
   [testng] 	at macaca.client.MacacaClient.elementsByClassName(MacacaClient.java:589)
   [testng] 	at com.mdm.test.function.MdmBase.modifyMdmUnlockPwd(MdmBase.java:128)
**重连也不行**
 [testng] org.apache.http.impl.execchain.RetryExec [master] main I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {}->http://localhost:3457: The target server failed to respond
   [testng] org.apache.http.impl.execchain.RetryExec [master] main Retrying request to {}->http://localhost:3457
   [testng] org.apache.http.impl.execchain.RetryExec [master] main I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {}->http://localhost:3457: The target server failed to respond
   [testng] org.apache.http.impl.execchain.RetryExec [master] main Retrying request to {}->http://localhost:3457


第二个也报这问题

启动多个任务 是不是由于usb监听导致的管道阻塞？ 

macaca quit之后
>> proxy.js:62:22 [master] pid:43694 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8900
>> proxy.js:62:22 [master] pid:43694 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8900
>> proxy.js:62:22 [master] pid:43694 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8900
>> proxy.js:62:22 [master] pid:43694 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8900
>> responseHandler.js:54:12 [master] pid:43694 Send Error Respone to Client: Error: connect ECONNREFUSED 127.0.0.1:8900
>> responseHandler.js:60:14 [master] pid:43694 Error: connect ECONNREFUSED 127.0.0.1:8900
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)

  Error: connect ECONNREFUSED 127.0.0.1:8900
      at Object.exports._errnoException (util.js:1026:11)
      at exports._exceptionWithHostPort (util.js:1049:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)

端口连不上了
命令查询并没有端口占用
![qq 20161208170341](https://cloud.githubusercontent.com/assets/8477313/21003869/876e4d2c-bd68-11e6-974a-5323abc627bc.png)

**Comment by ziczhu** [comment]
按道理说是可以同一个服务器处理不同连接的，都往 3456 端口发就可以了，不用多台服务器启动。不过后面倒是有个问题，就是如果两台真机端口都是 8900，那么 usb 代理的时候会把本机的 8900 指向两台手机的 8900，这样发来的请求就没法路由的，这么说，暂时好像是不能多机器的。

**Comment by jasonSky** [comment]
@zenzhu  好的 谢谢指导

**Comment by sixleaves** [comment]
@zenzhu 现在支持并发么？

**Comment by BeForever** [comment]
请问下，启动脚本后提示localhost：3456没有响应是什么情况呢
`org.apache.http.NoHttpResponseException: localhost:3456 failed to respond`
