### ISSUE TITLE
getproperty("value")方法报错

### ISSUE THREAD

**Issue by candialala** [macacajs/wd.java#82]
macacaclient-1.0.45.jar 若获取的value为boolean或String类型会报错
![image](https://cloud.githubusercontent.com/assets/22468260/21420323/1a527dfc-c868-11e6-89ad-bbce64e964dd.png)

**Comment by kobe990** [comment]
获取的是什么属性，贴下脚本看下，android还是ios，我这试了几个bool型的属性都ok的

**Comment by candialala** [comment]
@kobe990  是ios的

**Comment by huangejuan** [comment]
ios中getproperty("value")异常，因为返回的stringResponse值中value值不是JSONObject类型，而且stringResponse值中也没有label等值

**Comment by xudafeng** [comment]
https://github.com/alibaba/macaca/issues/468

**Comment by huangejuan** [comment]
@xudafeng  ios中Alert框中的属性信息getproperty获取不到？

**Comment by Yinxl** [comment]
getProperty的问题已经修复了，你这个具体信息是什么，能Inspect到对应alert框的对应property吗，具体可以加钉钉群：11775486 一起讨论下

**Comment by huangejuan** [comment]
@Yinxl  对的，能Inspector到对应Alert框的对应property值获取不到
